using System.ComponentModel.DataAnnotations;

namespace MyServerApp.Models
{
    public class Alert : BaseEntity
    {
        [Required]
        public int AssetId { get; set; }

        [Required]
        public int ZoneId { get; set; }

        [Required]
        [StringLength(50)]
        public string AlertType { get; set; } = "RESTRICTED_ZONE_ENTRY";

        [Required]
        [StringLength(255)]
        public string Title { get; set; } = string.Empty;

        [Required]
        public string Message { get; set; } = string.Empty;

        [Required]
        public AlertSeverity Severity { get; set; } = AlertSeverity.MEDIUM;

        public int IsRead { get; set; } = 0; // 0 = Unread, 1 = Read

        public DateTime? ReadAt { get; set; }

        [StringLength(100)]
        public string? ReadBy { get; set; }

        public int AutoGenerated { get; set; } = 1; // 1 = System generated, 0 = Manual

        // Navigation properties
        public virtual Asset? Asset { get; set; }
        public virtual Zone? Zone { get; set; }

        // Computed properties
        public bool IsUnread => IsRead == 0;
        public bool IsSystemGenerated => AutoGenerated == 1;
        public TimeSpan AlertAge => DateTime.Now - CreatedAt;
        public string SeverityColor => Severity switch
        {
            AlertSeverity.LOW => "#28a745",      // Green
            AlertSeverity.MEDIUM => "#ffc107",   // Yellow
            AlertSeverity.HIGH => "#fd7e14",     // Orange
            AlertSeverity.CRITICAL => "#dc3545", // Red
            _ => "#6c757d"                       // Gray
        };

        public string AlertTypeDisplayName => System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(AlertType.Replace("_", " ").ToLower());
    }

    // Enum for alert severity
    public enum AlertSeverity
    {
        LOW,
        MEDIUM,
        HIGH,
        CRITICAL
    }

    // Enum for alert types
    public enum AlertTypeEnum
    {
        RESTRICTED_ZONE_ENTRY,
        ASSET_TRANSFER,
        CAPACITY_EXCEEDED,
        ASSET_LOST,
        UNAUTHORIZED_ACCESS,
        MAINTENANCE_DUE,
        INSPECTION_REQUIRED,
        ZONE_OFFLINE,
        SYSTEM_ERROR
    }
}
